products = [
  {
    '_id': '1',
    'name': 'Apple AirPods Pro with Charging Case',
    'image': '/images/airpods.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers an immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 249.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Apple iPhone 12 Pro Max (128GB)',
    'image': '/images/phone.jpg',
    'description':
      "The iPhone 12 Pro Max are Apple's latest smartphones, offering 5G connectivity, the A14 chip for better performance, an improved camera system with a LiDAR scanner, and MagSafe, all in a new, squared-off design.",
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 1099.00,
    'countInStock': 20,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Garmin Vivoactive 3,',
    'image': '/images/watch.jpg',
    'description':
      'From playing to paying, vívoactive 3 is the smartwatch for your active life. Make contactless payments with ease, right from your watch, and with more than 15 preloaded sports apps — you can choose how you like to get fit. Built-in GPS lets you record the distance, pace, location and more for your outdoor activities.',
    'brand': 'Garmin',
    'category': 'Electronics',
    'price': 122.49,
    'countInStock': 50,
    'rating': 4.5,
    'numReviews': 70,
  },
  {
    '_id': '4',
    'name': 'Sony PlayStation 5 Console',
    'image': '/images/ps5.jpg',
    'description':
      'The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 499.99,
    'countInStock': 0,
    'rating': 5,
    'numReviews': 34,
  },
  {
    '_id': '5',
    'name': 'Logitech G502 Hero Gaming Mouse',
    'image': '/images/mouse.jpg',
    'description':
      "Logitech updated its iconic G502 gaming mouse to deliver even higher performance and more precise functionality than ever. Logitech G502 Hero high Performance Gaming mouse features the next generation Hero 16K Optical sensor, The highest performing and most efficient gaming sensor Logitech has ever made.",
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 79.99,
    'countInStock': 88,
    'rating': 3.5,
    'numReviews': 77,
  },
  {
    '_id': '6',
    'name': 'Sennheiser Momentum True Wireless 2',
    'image': '/images/SENNHEISER_Momentum_True_Wireless_2.jpg',
    'description':
      "Sennheiser's Momentum True Wireless 2 delivers exceptional sound quality with superior comfort and craftsmanship. Now you can enjoy Sennheiser's outstanding stereo sound anywhere and all day thanks to Active Noise Cancellation and an exceptional 7-hour battery life which can be extended to up to 28 hours via the charging case.",
    'brand': 'Sennheiser ',
    'category': 'Electronics',
    'price': 249.95,
    'countInStock': 0,
    'rating': 0,
    'numReviews': 0,
  },
    {
    '_id': '7',
    'name': 'Amazon Basics Carry-On Travel Backpack',
    'image': '/images/backpack.jpg',
    'description':
      'Carry-on travel backpack with internal, zippered laptop sleeve; ultra-flexible and lightweight; made of durable polyester',
    'brand': 'Amazon',
    'category': 'Luggage',
    'price': 54.45,
    'countInStock': 10,
    'rating': 0,
    'numReviews': 0,
  },
  {
    '_id': '8',
    'name': 'JBL FLIP 4 - Portable Bluetooth Speaker',
    'image': '/images/JBL.jpg',
    'description':
      'JBL Flip 4 is the next generation in the award-winning Flip series; it is a portable Bluetooth speaker that delivers surprisingly powerful stereo sound. This compact speaker is powered by a 3000mAh rechargeable Li-ion battery that offers 12 hours of continuous, high-quality audio playtime.',
    'brand': 'JBL',
    'category': 'Electronics',
    'price': 79.95,
    'countInStock': 99,
    'rating': 5,
    'numReviews': 88,
  },
  
]