products = [
  {
    '_id': '1',
    'name': 'Apple AirPods Pro with Charging Case',
    'image': '/images/airpods.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers an immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 249.00,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Apple iPhone 12 Pro Max (128GB)',
    'image': '/images/phone.jpg',
    'description':
      "The iPhone 12 Pro Max are Apple's latest smartphones, offering 5G connectivity, the A14 chip for better performance, an improved camera system with a LiDAR scanner, and MagSafe, all in a new, squared-off design.",
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 1099.00,
    'countInStock': 20,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Garmin Vivoactive 3 Smartwatch',
    'image': '/images/watch.jpg',
    'description':
      'From playing to paying, vívoactive 3 is the smartwatch for your active life. Make contactless payments with ease, right from your watch, and with more than 15 preloaded sports apps — you can choose how you like to get fit. Built-in GPS lets you record the distance, pace, location and more for your outdoor activities.',
    'brand': 'Garmin',
    'category': 'Electronics',
    'price': 122.49,
    'countInStock': 50,
    'rating': 4.5,
    'numReviews': 70,
  },
  {
    '_id': '4',
    'name': 'Sony PlayStation 5 Console',
    'image': '/images/ps5.jpg',
    'description':
      'The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 499.99,
    'countInStock': 0,
    'rating': 5,
    'numReviews': 34,
  },
  {
    '_id': '5',
    'name': 'Logitech G502 Hero Gaming Mouse',
    'image': '/images/mouse.jpg',
    'description':
      "Logitech updated its iconic G502 gaming mouse to deliver even higher performance and more precise functionality than ever. Logitech G502 Hero high Performance Gaming mouse features the next generation Hero 16K Optical sensor, The highest performing and most efficient gaming sensor Logitech has ever made.",
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 79.99,
    'countInStock': 88,
    'rating': 3.5,
    'numReviews': 77,
  },
  {
    '_id': '6',
    'name': 'Sennheiser Momentum True Wireless 2',
    'image': '/images/SENNHEISER_Momentum_True_Wireless_2.jpg',
    'description':
      "Sennheiser's Momentum True Wireless 2 delivers exceptional sound quality with superior comfort and craftsmanship. Now you can enjoy Sennheiser's outstanding stereo sound anywhere and all day thanks to Active Noise Cancellation and an exceptional 7-hour battery life which can be extended to up to 28 hours via the charging case.",
    'brand': 'Sennheiser ',
    'category': 'Electronics',
    'price': 249.95,
    'countInStock': 0,
    'rating': 0,
    'numReviews': 0,
  },
    {
    '_id': '7',
    'name': 'Amazon Basics Carry-On Travel Backpack',
    'image': '/images/backpack.jpg',
    'description':
      'Carry-on travel backpack with internal, zippered laptop sleeve; ultra-flexible and lightweight; made of durable polyester',
    'brand': 'Amazon',
    'category': 'Luggage',
    'price': 54.45,
    'countInStock': 10,
    'rating': 0,
    'numReviews': 0,
  },
  {
    '_id': '8',
    'name': 'JBL FLIP 4 - Portable Bluetooth Speaker',
    'image': '/images/JBL.jpg',
    'description':
      'JBL Flip 4 is the next generation in the award-winning Flip series; it is a portable Bluetooth speaker that delivers surprisingly powerful stereo sound. This compact speaker is powered by a 3000mAh rechargeable Li-ion battery that offers 12 hours of continuous, high-quality audio playtime.',
    'brand': 'JBL',
    'category': 'Electronics',
    'price': 79.95,
    'countInStock': 99,
    'rating': 5,
    'numReviews': 88,
  },
  {
    '_id': '9',
    'name': 'Google Nest Thermostat - Snow',
    'image': '/images/nest.jpg',
    'description':
      'Meet the Google Nest Thermostat, the smart thermostat for home with a cozy price. It can turn itself down to save energy when you leave the house. You can control this programmable thermostat from anywhere with the Google Home app – whether you’re on an errand or in bed.[1] And it’s simple to install yourself, usually in 30 minutes or less.',
    'brand': 'Google',
    'category': 'Electronics',
    'price': 129.00,
    'countInStock': 21,
    'rating': 4.5,
    'numReviews': 20,
  },
  {
    '_id': '10',
    'name': 'SAMSUNG T5 Portable SSD 1TB',
    'image': '/images/samsung_t5.jpg',
    'description':
      'The SAMSUNG T5 Portable SSD has the latest in SAMSUNG V-NAND flash memory technology. Its portable design, blazing fast transfer speeds of up to 540 MB/s, shock resistance, and secure encryption make it the best portable SSD on the market.',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 129.99,
    'countInStock': 4,
    'rating': 5,
    'numReviews': 67,
  },
  {
    '_id': '11',
    'name': 'Amazon eero mesh WiFi system',
    'image': '/images/amazon_wifi.jpg',
    'description':
      'eero 6 systems use the power of Wi-Fi 6 to deliver faster speeds, increase your internet’s efficiency, and reduce network congestion. Say goodbye to dead spots and buffering with a connection that doesn’t slow you down, even as you add more devices.',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 169.00,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 57,
  },
  {
    '_id': '12',
    'name': 'SAMSUNG Galaxy Watch Active 2',
    'image': '/images/samsung_watch.jpg',
    'description':
      'The SAMSUNG Galaxy Watch Active 2 is designed to help you learn more So you can achieve more. It goes beyond tracking steps And calories to offer actionable insights on everything from your running style to your heart rate. Connect seamlessly via Bluetooth to your favorite apps so you can keep moving and a sleek, all-new design means you can wear the Galaxy Watch Active 2 everywhere from the gym to the pool to your bed.',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 199.99,
    'countInStock': 66,
    'rating': 3.5,
    'numReviews': 12,
  },
  {
    '_id': '13',
    'name': 'Razer Blade 15 Base Gaming Laptop 2020',
    'image': '/images/razer_laptop.jpg',
    'description':
      'The new Razer Blade 15 is an ultra-compact NVIDIA GeForce powered laptop that features the latest 10th Gen Intel Core i7 6-core processor, to deliver amazing performance and portability. The 15.6" 120Hz thin bezel Full HD display provides an immersive and insanely fast visual experience for gaming and beyond.',
    'brand': 'Razer',
    'category': 'Electronics',
    'price': 1199.99,
    'countInStock': 2,
    'rating': 4.5,
    'numReviews': 28,
  },
]