# Generated by Django 3.1.7 on 2021-04-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210419_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliverdAt',
            new_name='deliveredAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='creactedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
